### ISSUE TITLE
Bring up easy-jenkins on AWS instance

### ISSUE THREAD

**Issue by gmacario** [rokers-reply/rokers-hunting-razerblade#17]
AWS instance provided by @ludusrusso , see credentials on Telegram

**Comment by gmacario** [comment]
@ludusrusso did you already shutdown the AWS instance?

**Comment by ludusrusso** [comment]
Yes!

**Comment by gmacario** [comment]
OK, I will bring easy-jenkins up once you provide me my well deserved https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/
